### ISSUE TITLE
Actor count misleading

### ISSUE THREAD

**Issue by janm399** [eigengo/monitor#39]
The actor count metric is—at best—misleading. Investigate using a _gauge_ rather than _counter_ for it.

**Comment by janm399** [comment]
Any progress here?

**Comment by hughsimpson** [comment]
I had a look at using histograms and gauge, but although we could log some different values (e.g. some integer or float representation of the actor ref) there doesn't appear to be any way of displaying the number of different values in datadog. I had a look at using tags, instead, but although there's a configuration to 'display by tag', it wouldn't provide us with an actual metric of the number of actors, but just a separate graph for each actor (which is fine if you have 3, but....). Also, that doesn't work anyway. So: the only thing I can see that's appropriate -- unless we can catch _all_ of the pointcuts that cause actor death (and I'm nervous about that, since I don't see how we can do that reliably, and we _still_ have the issue of displaying the metric) -- is using datadog's 'set' method (display number of unique values in a collection). But that means that we need to implement our own StatsD client. Which is sort of what I'm looking at doing -- I'll keep at it over the weekend and hope to have something working for Monday.

**Comment by janm399** [comment]
If DD can display values such as free memory, disk space, etc; then why is it not possible to show the number of actors? There are only two ways to create an actor: the `actorOf` method in `ActorSystem` and `ActorCell`. 
The task to explore is the way to detect actor destruction.

Once you have that—and I suggest that the code we currently have does good enough job—you need to keep a count of actors per actor system. Essentially, a 

``` java
public aspect ... {
    private Map<String, Integer> actorCounts = Collections.synchronizedMap(new HashMap<...>());

}
```

On creation, find the value for the actor system, increment it and report it on a gauge, tagged with the actor system. On destruction, do the same, but decrementing.

**Comment by archena** [comment]
@hughsimpson Why would you need your own statsd client? https://github.com/youdevise/java-statsd-client claims to include Datadog-specific extensions to Statsd, but if it doesn't support sets, couldn't you extend it?

@janm399 or `ConcurrentHashMap`? with more fine-grained locking.

**Comment by janm399** [comment]
@archena +1 for `ConcurrentHashMap`, but let's just get something going; I also think that @hughsimpson is referring to statsd _server_ and _client_. But there's no need for either of them.
